server.port=8080

# H2 Database Configuration (Relational in-memory)
spring.datasource.url=jdbc:h2:file:./data/torneos_ajedrez
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console to replace pgAdmin
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS (Para simplificar en API Basica)
spring.mvc.cors.allowed-origins=*
